# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      # Download and cache dependencies

      # composer install

      - restore_cache:
          keys:
            # "composer.json" can be used if "composer.json"
            # is not committed to the repository.
            - v1-composer-deps-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-composer-deps-

      - run:
          name: Composer Install
          command: |
            composer install -n --prefer-dist
          environment:
            ACF_PRO_KEY: b3JkZXJfaWQ9OTE3MTh8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE2LTEwLTE0IDE5OjE5OjA2

      - save_cache:
          key: v1-composer-deps-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # npm install

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "app/themes/wlion/package-lock.json" }}
            - v1-npm-deps-

      - run:
          name: NPM Install
          command: |
            cd app/themes/wlion
            npm install

      - save_cache:
          key: v1-npm-deps-{{ checksum "app/themes/wlion/package-lock.json" }}
          paths:
            - app/themes/wlion/node_modules

      # npm build

      - run:
          name: NPM Run Build
          command: |
            cd app/themes/wlion
            npm run build

      # persist composer packages and build files to workspace

      - persist_to_workspace:
          root: ./
          paths:
            - vendor
            - wp
            - app/plugins
            - app/themes/wlion/build

      # - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      # - run: sudo docker-php-ext-install zip

  deploy:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout

      # attach composer packages and build files to workspace

      - attach_workspace:
          at: ./

      - add_ssh_keys:
          fingerprints:
            - "9e:a6:91:49:29:17:ef:aa:02:6d:c8:ed:a5:63:5b:5a"
            - "SHA256:LD1S1g9Jvq+WG3AyiAcgl1l5jFGKKJv/fFDxBSBl08Q"
            - "SHA256:z6N4CNYSDyNAG4i40CrK5jvfWbfXFENXtr+HQtXTJWc"

      - run: |
          ls -la
          git remote add review wlion@web8.wlion.com:git/pt-wordpress-composer.git
          git push review

      # - run:
      #     name: Remove .gitignore file
      #     command: |
      #       rm --rf .gitignore
      #       mv .gitignore-deploy .gitignore

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
